create_tec_news_job:
  cron: "0 * * * *"
  class: "CreateTecNewsJob"   
  queue: default 

create_world_news_job:
  cron: "0 * * * *"
  class: "CreateWorldNewsJob"   
  queue: default 

create_entertainment_news_job:
  cron: "0 * * * *"
  class: "CreateEntertainmentNewsJob"   
  queue: default   